### ISSUE TITLE
Help! Server won't start and I'm completely lost!

### ISSUE THREAD

**Issue by letsalllovelain** [hzoo/TwitchPlaysX#11]
This is what I ended up doing, I made a new Config.JSON with the following as the information without touching the config.jn file. Is this what i'm supposed to do? Where do I save the Config-JSON file??

{
    
    "TWITCH_OAUTH": "My oauth key",
    "TWITCH_USERNAME": "twitch username",
    "TWITCH_CHANNEL": "twitch username",
    "CONFIG_OS": "windows",
    "CONFIG_PROGRAM_NAME": "ePSXe",
    "CONFIG_MAX_CHAR_NAME": 8,
    "CONFIG_MAX_CHAR_COMMAND": 20,
    "CONFIG_SEND_KEY": true,
    "CONFIG_FILTERED_COMMANDS": [],
    "CONFIG_THROTTLED_COMMANDS": []
}

    "TWITCH_USERNAME": "TWITCH_NAME_HERE",
    "TWITCH_CHANNEL": "#CHANNEL_HERE",

Is the channel name and the username the same thing in the config for twitch?

I managed to get the package.json installed by moving the file (https://github.com/hzoo/TwitchPlaysX/archive/master.zip) to the node modules directory. I typed "npm install" and it magically worked. Now my problem is that the sever refuses to start, I type "npm start" as said in the tutorial and this is what it tells me:

npm start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\userl\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\user\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-04-26T09_51_38_769Z-debug.log
the tutorial said something about "path" being python, but its already set as path in system variables.

Thanks for the help.

**Comment by hzoo** [comment]
Made a bunch of updates (just removed that config file entirely) so I would check out master again and  rerun: https://github.com/hzoo/TwitchPlaysX#setup
