### ISSUE TITLE
Stuck on Connecting

### ISSUE THREAD

**Issue by nrosver** [hzoo/TwitchPlaysX#5]
i start the app with npm start, and it just get stuck on Connecting...

I already setup config.json

**Comment by wblamkin** [comment]
Hi, I am also having this problem. I'd like to be able to use this program, but unfortunately cannot get beyond this step.

**Comment by William-Carter** [comment]
Are you sure that it's stuck? It doesn't actually say "complete" after it's done. Just send a signal through.

**Comment by BGP19000** [comment]
I am also having the same problem, have any of you figured it out? Also, it is stuck, it won't let me type anything.

**Comment by hzoo** [comment]
Merged https://github.com/hzoo/TwitchPlaysX/pull/9 so I would try checking out master again to see if it works

**Comment by hzoo** [comment]
https://github.com/hzoo/TwitchPlaysX#setup ok made a bunch of updates to simplify things (just fyi I haven't watched the repo in years so didn't get any notifications for it haha!)
