### ISSUE TITLE
Server not working

### ISSUE THREAD

**Issue by Vrubi** [hzoo/TwitchPlaysX#6]
Hello, I have configured and installed everything (in theorie), but this thing still won't run. Here is the Debug file: 

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Programok\\Node.js\\node.exe',
1 verbose cli   'D:\\Programok\\Node.js\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle TwitchPlaysX@0.0.1~prestart: TwitchPlaysX@0.0.1
6 silly lifecycle TwitchPlaysX@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle TwitchPlaysX@0.0.1~start: TwitchPlaysX@0.0.1
8 verbose lifecycle TwitchPlaysX@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle TwitchPlaysX@0.0.1~start: PATH: D:\Programok\Node.js\node_modules\npm\bin\node-gyp-bin;C:\Users\Bence\Desktop\TwitchPlaysX-master\node_modules\.bin;D:\Programok\Git\cmd;D:\Programok\Python\;C:\Program Files (x86)\PC Connectivity Solution\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\doxygen\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;D:\Programok\Node.js\;C:\Users\Bence\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;D:\Programok\Git\cmd;C:\Users\Bence\AppData\Local\Microsoft\WindowsApps;C:\Users\Bence\AppData\Roaming\npm
10 verbose lifecycle TwitchPlaysX@0.0.1~start: CWD: C:\Users\Bence\Desktop\TwitchPlaysX-master
11 silly lifecycle TwitchPlaysX@0.0.1~start: Args: [ '/d /s /c', 'node ./app/server' ]
12 silly lifecycle TwitchPlaysX@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle TwitchPlaysX@0.0.1~start: Failed to exec start script
14 verbose stack Error: TwitchPlaysX@0.0.1 start: `node ./app/server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (D:\Programok\Node.js\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\Programok\Node.js\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid TwitchPlaysX@0.0.1
16 verbose cwd C:\Users\Bence\Desktop\TwitchPlaysX-master
17 error Windows_NT 10.0.14393
18 error argv "D:\\Programok\\Node.js\\node.exe" "D:\\Programok\\Node.js\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.2
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error TwitchPlaysX@0.0.1 start: `node ./app/server`
22 error Exit status 1
23 error Failed at the TwitchPlaysX@0.0.1 start script 'node ./app/server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the TwitchPlaysX package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./app/server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs TwitchPlaysX
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls TwitchPlaysX
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Honestly i have no idea what the problem could be. Hope you can help me out! :)

**Comment by kasplat** [comment]
Late, but for anyone else that sees, updating to the latest versions of npm and nodejs fixed the issue for me.

**Comment by hzoo** [comment]
Yeah I would recommend updating both, maybe clearing your node_modules!
